### ISSUE TITLE
Null rows in CSV files without a header

### ISSUE THREAD

**Issue by JGSweets** [capitalone/DataProfiler#196]
**General Information:**
 - OS: macOS
 - Python version: 3.8.7
 - Library version: v0.4.4

**Describe the bug:**
Not able to skip blank lines in data without a header

**To Reproduce:**

The pandas issue which causes our `CSVData` to fail.
```python
import pandas as pd
from io import StringIO
s = """
1


4"""
pd.read_csv(StringIO(s), header=None, skip_blank_lines=False)
```

Should fail with our reader as such (IF we took in StringIO, need to create this data as a file):
```python
import dataprofiler as dp
from io import StringIO
s = """
1


4"""
data = dp.Data(s)
```

**Expected behavior:**
data frame should be either:
1, NaN,  NaN,  4
or
NaN, 1, NaN,  NaN,  4

However we get:
1,4

**Additional context:**

**Comment by lettergram** [comment]
This is a Pandas error and thus far there doesn't seem to be a perfect solution.

PR #193 does mitigate this issue somewhat. If a header is identified the library will now set `skip_blank_lines` to `False`, however if a header is not identified the `skip_blank_lines` is set to default (`True`). If the `skip_blank_lines` is set to `False` and a header is not set, then it'll error. 

At this point, this issue is in Pandas hands, it shouldn't error, it should set no header.
